// Generated by gencpp from file path_tracking/ModelParameter.msg
// DO NOT EDIT!


#ifndef PATH_TRACKING_MESSAGE_MODELPARAMETER_H
#define PATH_TRACKING_MESSAGE_MODELPARAMETER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace path_tracking
{
template <class ContainerAllocator>
struct ModelParameter_
{
  typedef ModelParameter_<ContainerAllocator> Type;

  ModelParameter_()
    : header()
    , speed_parameter(0.0)
    , steer_parameter(0.0)
    , time_cost(0.0)  {
    }
  ModelParameter_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , speed_parameter(0.0)
    , steer_parameter(0.0)
    , time_cost(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _speed_parameter_type;
  _speed_parameter_type speed_parameter;

   typedef double _steer_parameter_type;
  _steer_parameter_type steer_parameter;

   typedef double _time_cost_type;
  _time_cost_type time_cost;





  typedef boost::shared_ptr< ::path_tracking::ModelParameter_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::path_tracking::ModelParameter_<ContainerAllocator> const> ConstPtr;

}; // struct ModelParameter_

typedef ::path_tracking::ModelParameter_<std::allocator<void> > ModelParameter;

typedef boost::shared_ptr< ::path_tracking::ModelParameter > ModelParameterPtr;
typedef boost::shared_ptr< ::path_tracking::ModelParameter const> ModelParameterConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::path_tracking::ModelParameter_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::path_tracking::ModelParameter_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace path_tracking

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'path_tracking': ['/home/bit2/0603_project/tang_ws/src/control/path_tracking/msg'], 'control_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/control_msgs/msg'], 'sensor_driver_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/sensor_driver_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'anm_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/anm_msgs/msg'], 'dbw_mkz_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/dbw_mkz_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::path_tracking::ModelParameter_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::path_tracking::ModelParameter_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_tracking::ModelParameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::path_tracking::ModelParameter_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_tracking::ModelParameter_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::path_tracking::ModelParameter_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::path_tracking::ModelParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "564bf96590ff731beab91211a6911188";
  }

  static const char* value(const ::path_tracking::ModelParameter_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x564bf96590ff731bULL;
  static const uint64_t static_value2 = 0xeab91211a6911188ULL;
};

template<class ContainerAllocator>
struct DataType< ::path_tracking::ModelParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "path_tracking/ModelParameter";
  }

  static const char* value(const ::path_tracking::ModelParameter_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::path_tracking::ModelParameter_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
\n\
float64 speed_parameter\n\
float64 steer_parameter\n\
float64 time_cost\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::path_tracking::ModelParameter_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::path_tracking::ModelParameter_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.speed_parameter);
      stream.next(m.steer_parameter);
      stream.next(m.time_cost);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ModelParameter_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::path_tracking::ModelParameter_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::path_tracking::ModelParameter_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "speed_parameter: ";
    Printer<double>::stream(s, indent + "  ", v.speed_parameter);
    s << indent << "steer_parameter: ";
    Printer<double>::stream(s, indent + "  ", v.steer_parameter);
    s << indent << "time_cost: ";
    Printer<double>::stream(s, indent + "  ", v.time_cost);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PATH_TRACKING_MESSAGE_MODELPARAMETER_H
