// Generated by gencpp from file vertical_wall_grid/vertical_wall_grid.msg
// DO NOT EDIT!


#ifndef VERTICAL_WALL_GRID_MESSAGE_VERTICAL_WALL_GRID_H
#define VERTICAL_WALL_GRID_MESSAGE_VERTICAL_WALL_GRID_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace vertical_wall_grid
{
template <class ContainerAllocator>
struct vertical_wall_grid_
{
  typedef vertical_wall_grid_<ContainerAllocator> Type;

  vertical_wall_grid_()
    : header()
    , detected(false)
    , dis(0.0)
    , angle(0.0)
    , height(0.0)
    , center()
    , vertical(false)  {
      center.assign(0.0);
  }
  vertical_wall_grid_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , detected(false)
    , dis(0.0)
    , angle(0.0)
    , height(0.0)
    , center()
    , vertical(false)  {
  (void)_alloc;
      center.assign(0.0);
  }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef uint8_t _detected_type;
  _detected_type detected;

   typedef float _dis_type;
  _dis_type dis;

   typedef float _angle_type;
  _angle_type angle;

   typedef float _height_type;
  _height_type height;

   typedef boost::array<float, 2>  _center_type;
  _center_type center;

   typedef uint8_t _vertical_type;
  _vertical_type vertical;





  typedef boost::shared_ptr< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> const> ConstPtr;

}; // struct vertical_wall_grid_

typedef ::vertical_wall_grid::vertical_wall_grid_<std::allocator<void> > vertical_wall_grid;

typedef boost::shared_ptr< ::vertical_wall_grid::vertical_wall_grid > vertical_wall_gridPtr;
typedef boost::shared_ptr< ::vertical_wall_grid::vertical_wall_grid const> vertical_wall_gridConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vertical_wall_grid

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'vertical_wall_grid': ['/home/bit2/0603_project/tang_ws/src/msgs/vertical_wall_grid_msg/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f060965c53a68944b55190b69cd4980c";
  }

  static const char* value(const ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf060965c53a68944ULL;
  static const uint64_t static_value2 = 0xb55190b69cd4980cULL;
};

template<class ContainerAllocator>
struct DataType< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vertical_wall_grid/vertical_wall_grid";
  }

  static const char* value(const ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
bool detected\n\
float32 dis\n\
float32 angle\n\
float32 height\n\
float32[2] center\n\
bool vertical\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.detected);
      stream.next(m.dis);
      stream.next(m.angle);
      stream.next(m.height);
      stream.next(m.center);
      stream.next(m.vertical);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct vertical_wall_grid_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vertical_wall_grid::vertical_wall_grid_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "detected: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.detected);
    s << indent << "dis: ";
    Printer<float>::stream(s, indent + "  ", v.dis);
    s << indent << "angle: ";
    Printer<float>::stream(s, indent + "  ", v.angle);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "center[]" << std::endl;
    for (size_t i = 0; i < v.center.size(); ++i)
    {
      s << indent << "  center[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.center[i]);
    }
    s << indent << "vertical: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.vertical);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VERTICAL_WALL_GRID_MESSAGE_VERTICAL_WALL_GRID_H
