//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the chassis_testing package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __chassis_testing__STATICTESTINGCONFIG_H__
#define __chassis_testing__STATICTESTINGCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace chassis_testing
{
  class StaticTestingConfigStatics;

  class StaticTestingConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(StaticTestingConfig &config, const StaticTestingConfig &max, const StaticTestingConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const StaticTestingConfig &config1, const StaticTestingConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, StaticTestingConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const StaticTestingConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, StaticTestingConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const StaticTestingConfig &config) const = 0;
      virtual void getValue(const StaticTestingConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T StaticTestingConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (StaticTestingConfig::* field);

      virtual void clamp(StaticTestingConfig &config, const StaticTestingConfig &max, const StaticTestingConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const StaticTestingConfig &config1, const StaticTestingConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, StaticTestingConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const StaticTestingConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, StaticTestingConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const StaticTestingConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const StaticTestingConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, StaticTestingConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, StaticTestingConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<StaticTestingConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(StaticTestingConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("gear"==(*_i)->name){gear = boost::any_cast<int>(val);}
        if("target_speed"==(*_i)->name){target_speed = boost::any_cast<double>(val);}
        if("target_acceleration"==(*_i)->name){target_acceleration = boost::any_cast<double>(val);}
        if("halt"==(*_i)->name){halt = boost::any_cast<double>(val);}
        if("steer_mode"==(*_i)->name){steer_mode = boost::any_cast<int>(val);}
        if("steer_degree"==(*_i)->name){steer_degree = boost::any_cast<int>(val);}
        if("steer_radius"==(*_i)->name){steer_radius = boost::any_cast<double>(val);}
        if("left_light"==(*_i)->name){left_light = boost::any_cast<bool>(val);}
        if("right_light"==(*_i)->name){right_light = boost::any_cast<bool>(val);}
      }
    }

    int gear;
double target_speed;
double target_acceleration;
double halt;
int steer_mode;
int steer_degree;
double steer_radius;
bool left_light;
bool right_light;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int gear;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_speed;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double target_acceleration;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double halt;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int steer_mode;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int steer_degree;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double steer_radius;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool left_light;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      bool right_light;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("StaticTestingConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const StaticTestingConfig &__max__ = __getMax__();
      const StaticTestingConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const StaticTestingConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const StaticTestingConfig &__getDefault__();
    static const StaticTestingConfig &__getMax__();
    static const StaticTestingConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const StaticTestingConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void StaticTestingConfig::ParamDescription<std::string>::clamp(StaticTestingConfig &config, const StaticTestingConfig &max, const StaticTestingConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class StaticTestingConfigStatics
  {
    friend class StaticTestingConfig;

    StaticTestingConfigStatics()
    {
StaticTestingConfig::GroupDescription<StaticTestingConfig::DEFAULT, StaticTestingConfig> Default("Default", "", 0, 0, true, &StaticTestingConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.gear = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.gear = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.gear = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<int>("gear", "int", 0, "Gear", "{'enum_description': 'An enum to gear', 'enum': [{'srcline': 7, 'description': 'P gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'P'}, {'srcline': 8, 'description': 'N gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'N'}, {'srcline': 9, 'description': 'R gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'R'}, {'srcline': 10, 'description': 'D gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'D'}]}", &StaticTestingConfig::gear)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<int>("gear", "int", 0, "Gear", "{'enum_description': 'An enum to gear', 'enum': [{'srcline': 7, 'description': 'P gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'P'}, {'srcline': 8, 'description': 'N gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'N'}, {'srcline': 9, 'description': 'R gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'R'}, {'srcline': 10, 'description': 'D gear', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'D'}]}", &StaticTestingConfig::gear)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_speed = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_speed = 40.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_speed = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("target_speed", "double", 0, "Target speed", "", &StaticTestingConfig::target_speed)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("target_speed", "double", 0, "Target speed", "", &StaticTestingConfig::target_speed)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.target_acceleration = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.target_acceleration = 10.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.target_acceleration = 0.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("target_acceleration", "double", 0, "Target acceleration", "", &StaticTestingConfig::target_acceleration)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("target_acceleration", "double", 0, "Target acceleration", "", &StaticTestingConfig::target_acceleration)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.halt = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.halt = 30;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.halt = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("halt", "bool", 0, "Halt", "", &StaticTestingConfig::halt)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("halt", "bool", 0, "Halt", "", &StaticTestingConfig::halt)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_mode = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_mode = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_mode = 2;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<int>("steer_mode", "int", 0, "Steer mode", "{'enum_description': 'An enum to steer mode', 'enum': [{'srcline': 16, 'description': 'Mode : Center turn', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Center_turn'}, {'srcline': 17, 'description': 'Mode : Turn around', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Turn_around'}, {'srcline': 18, 'description': 'Mode : Steering', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Steering'}]}", &StaticTestingConfig::steer_mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<int>("steer_mode", "int", 0, "Steer mode", "{'enum_description': 'An enum to steer mode', 'enum': [{'srcline': 16, 'description': 'Mode : Center turn', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'Center_turn'}, {'srcline': 17, 'description': 'Mode : Turn around', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'Turn_around'}, {'srcline': 18, 'description': 'Mode : Steering', 'srcfile': '/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'Steering'}]}", &StaticTestingConfig::steer_mode)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_degree = -30;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_degree = 30;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_degree = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<int>("steer_degree", "int", 0, "Steer degree", "", &StaticTestingConfig::steer_degree)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<int>("steer_degree", "int", 0, "Steer degree", "", &StaticTestingConfig::steer_degree)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.steer_radius = -100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.steer_radius = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.steer_radius = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("steer_radius", "double", 0, "Steer radius", "", &StaticTestingConfig::steer_radius)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<double>("steer_radius", "double", 0, "Steer radius", "", &StaticTestingConfig::steer_radius)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.left_light = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.left_light = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.left_light = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<bool>("left_light", "bool", 0, "Left steer light", "", &StaticTestingConfig::left_light)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<bool>("left_light", "bool", 0, "Left steer light", "", &StaticTestingConfig::left_light)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.right_light = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.right_light = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.right_light = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<bool>("right_light", "bool", 0, "Right steer light", "", &StaticTestingConfig::right_light)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(StaticTestingConfig::AbstractParamDescriptionConstPtr(new StaticTestingConfig::ParamDescription<bool>("right_light", "bool", 0, "Right steer light", "", &StaticTestingConfig::right_light)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(StaticTestingConfig::AbstractGroupDescriptionConstPtr(new StaticTestingConfig::GroupDescription<StaticTestingConfig::DEFAULT, StaticTestingConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<StaticTestingConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<StaticTestingConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<StaticTestingConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    StaticTestingConfig __max__;
    StaticTestingConfig __min__;
    StaticTestingConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const StaticTestingConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static StaticTestingConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &StaticTestingConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const StaticTestingConfig &StaticTestingConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const StaticTestingConfig &StaticTestingConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const StaticTestingConfig &StaticTestingConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<StaticTestingConfig::AbstractParamDescriptionConstPtr> &StaticTestingConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<StaticTestingConfig::AbstractGroupDescriptionConstPtr> &StaticTestingConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const StaticTestingConfigStatics *StaticTestingConfig::__get_statics__()
  {
    const static StaticTestingConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = StaticTestingConfigStatics::get_instance();

    return statics;
  }

//#line 7 "/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg"
      const int StaticTesting_P = 0;
//#line 8 "/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg"
      const int StaticTesting_N = 1;
//#line 9 "/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg"
      const int StaticTesting_R = 2;
//#line 10 "/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg"
      const int StaticTesting_D = 3;
//#line 16 "/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg"
      const int StaticTesting_Center_turn = 0;
//#line 17 "/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg"
      const int StaticTesting_Turn_around = 1;
//#line 18 "/home/zcl/Desktop/chassis/src/chassis_testing/config/StaticTesting.cfg"
      const int StaticTesting_Steering = 2;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __STATICTESTINGRECONFIGURATOR_H__
