# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from three_one_msgs/ControlSuspension.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ControlSuspension(genpy.Message):
  _md5sum = "4bc4d758b88c322981bcdaff503bd5e7"
  _type = "three_one_msgs/ControlSuspension"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """uint8 priority
uint8 cylinder_select
uint8 suspension_select
uint8 suspension_work_mode
uint8 suspension_work_mode_detail
uint8 suspension_cylinder_select_mode
uint8 suspension_cylinder_motor_control
uint8 vertical_wall_mode
uint8 fix_two_chamber_valve
uint8 entrenchment"""
  __slots__ = ['priority','cylinder_select','suspension_select','suspension_work_mode','suspension_work_mode_detail','suspension_cylinder_select_mode','suspension_cylinder_motor_control','vertical_wall_mode','fix_two_chamber_valve','entrenchment']
  _slot_types = ['uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       priority,cylinder_select,suspension_select,suspension_work_mode,suspension_work_mode_detail,suspension_cylinder_select_mode,suspension_cylinder_motor_control,vertical_wall_mode,fix_two_chamber_valve,entrenchment

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ControlSuspension, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.priority is None:
        self.priority = 0
      if self.cylinder_select is None:
        self.cylinder_select = 0
      if self.suspension_select is None:
        self.suspension_select = 0
      if self.suspension_work_mode is None:
        self.suspension_work_mode = 0
      if self.suspension_work_mode_detail is None:
        self.suspension_work_mode_detail = 0
      if self.suspension_cylinder_select_mode is None:
        self.suspension_cylinder_select_mode = 0
      if self.suspension_cylinder_motor_control is None:
        self.suspension_cylinder_motor_control = 0
      if self.vertical_wall_mode is None:
        self.vertical_wall_mode = 0
      if self.fix_two_chamber_valve is None:
        self.fix_two_chamber_valve = 0
      if self.entrenchment is None:
        self.entrenchment = 0
    else:
      self.priority = 0
      self.cylinder_select = 0
      self.suspension_select = 0
      self.suspension_work_mode = 0
      self.suspension_work_mode_detail = 0
      self.suspension_cylinder_select_mode = 0
      self.suspension_cylinder_motor_control = 0
      self.vertical_wall_mode = 0
      self.fix_two_chamber_valve = 0
      self.entrenchment = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_10B().pack(_x.priority, _x.cylinder_select, _x.suspension_select, _x.suspension_work_mode, _x.suspension_work_mode_detail, _x.suspension_cylinder_select_mode, _x.suspension_cylinder_motor_control, _x.vertical_wall_mode, _x.fix_two_chamber_valve, _x.entrenchment))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.priority, _x.cylinder_select, _x.suspension_select, _x.suspension_work_mode, _x.suspension_work_mode_detail, _x.suspension_cylinder_select_mode, _x.suspension_cylinder_motor_control, _x.vertical_wall_mode, _x.fix_two_chamber_valve, _x.entrenchment,) = _get_struct_10B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_10B().pack(_x.priority, _x.cylinder_select, _x.suspension_select, _x.suspension_work_mode, _x.suspension_work_mode_detail, _x.suspension_cylinder_select_mode, _x.suspension_cylinder_motor_control, _x.vertical_wall_mode, _x.fix_two_chamber_valve, _x.entrenchment))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 10
      (_x.priority, _x.cylinder_select, _x.suspension_select, _x.suspension_work_mode, _x.suspension_work_mode_detail, _x.suspension_cylinder_select_mode, _x.suspension_cylinder_motor_control, _x.vertical_wall_mode, _x.fix_two_chamber_valve, _x.entrenchment,) = _get_struct_10B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_10B = None
def _get_struct_10B():
    global _struct_10B
    if _struct_10B is None:
        _struct_10B = struct.Struct("<10B")
    return _struct_10B
