(cl:in-package three_one_msgs-msg)
(cl:export '(PRIORITY-VAL
          PRIORITY
          CYLINDER_SELECT-VAL
          CYLINDER_SELECT
          SUSPENSION_SELECT-VAL
          SUSPENSION_SELECT
          SUSPENSION_WORK_MODE-VAL
          SUSPENSION_WORK_MODE
          SUSPENSION_WORK_MODE_DETAIL-VAL
          SUSPENSION_WORK_MODE_DETAIL
          SUSPENSION_CYLINDER_SELECT_MODE-VAL
          SUSPENSION_CYLINDER_SELECT_MODE
          SUSPENSION_CYLINDER_MOTOR_CONTROL-VAL
          SUSPENSION_CYLINDER_MOTOR_CONTROL
          VERTICAL_WALL_MODE-VAL
          VERTICAL_WALL_MODE
          FIX_TWO_CHAMBER_VALVE-VAL
          FIX_TWO_CHAMBER_VALVE
          ENTRENCHMENT-VAL
          ENTRENCHMENT
))