# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from path_tracking/observer.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import anm_msgs.msg
import control_msgs.msg
import std_msgs.msg

class observer(genpy.Message):
  _md5sum = "5f683c55d076db2e680be51e6dee7354"
  _type = "path_tracking/observer"
  _has_header = True #flag to mark the presence of a Header object
  _full_text = """Header header

anm_msgs/VehicleState vehicle_state
control_msgs/Report ecu_report
float64 speed_cmd
float64 steer_cmd
float64 lateral_error
float64 heading_error
float64 time_cost

================================================================================
MSG: std_msgs/Header
# Standard metadata for higher-level stamped data types.
# This is generally used to communicate timestamped data 
# in a particular coordinate frame.
# 
# sequence ID: consecutively increasing ID 
uint32 seq
#Two-integer timestamp that is expressed as:
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')
# time-handling sugar is provided by the client library
time stamp
#Frame this data is associated with
# 0: no frame
# 1: global frame
string frame_id

================================================================================
MSG: anm_msgs/VehicleState
# This message describes the complete vehicle state
# orientation = orientation of the vehicle using euler angles

Header header
string child_frame_id

geometry_msgs/Point position
geometry_msgs/Vector3 orientation
geometry_msgs/Twist velocity
geometry_msgs/Twist acceleration

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

================================================================================
MSG: geometry_msgs/Vector3
# This represents a vector in free space. 
# It is only meant to represent a direction. Therefore, it does not
# make sense to apply a translation to it (e.g., when applying a 
# generic rigid transformation to a Vector3, tf2 will only apply the
# rotation). If you want your data to be translatable too, use the
# geometry_msgs/Point message instead.

float64 x
float64 y
float64 z
================================================================================
MSG: geometry_msgs/Twist
# This expresses velocity in free space broken into its linear and angular parts.
Vector3  linear
Vector3  angular

================================================================================
MSG: control_msgs/Report
Header header
ReportControl control

ReportControl vcu_torque_brake

ReportMotion motion
ReportBrake brake
ReportThrottle throttle
ReportWheel wheel
ReportHMI manual
ReportVehicleWorkMode vehicle_work_mode 

================================================================================
MSG: control_msgs/ReportControl
ControlSpeed Speed
ControlSteer Steer
ControlMode ordermode


================================================================================
MSG: control_msgs/ControlSpeed
Header header
uint8 priority
uint8 gear
float64 speed
float64 acc
float64 torque
float64 brake

================================================================================
MSG: control_msgs/ControlSteer
Header header
uint8 priority
float64 steer


================================================================================
MSG: control_msgs/ControlMode
Header header
uint8 RainyLight



================================================================================
MSG: control_msgs/ReportMotion
uint8 drive_mode
float64 steer
uint8 gear
float64 velocity



================================================================================
MSG: control_msgs/ReportBrake
float64 left_pressure_back
float64 right_pressure_back
uint8 auto_park_state
uint8 auto_brake_enable
uint8 system_hot_warn
uint8 system_error_code
float64 left_pressure_set
float64 right_pressure_set
float32 brake_pedal

================================================================================
MSG: control_msgs/ReportThrottle
float32 throttle_opening
float32 throttle_pedal

================================================================================
MSG: control_msgs/ReportWheel
float32 front_left
float32 front_right
float32 rear_left
float32 rear_right
uint8 statusfl
uint8 statusfr
uint8 statusrl
uint8 statusrr

================================================================================
MSG: control_msgs/ReportHMI
uint8 manual_estop
uint8 is_human_brake 

================================================================================
MSG: control_msgs/ReportVehicleWorkMode
uint8 work_mode


"""
  __slots__ = ['header','vehicle_state','ecu_report','speed_cmd','steer_cmd','lateral_error','heading_error','time_cost']
  _slot_types = ['std_msgs/Header','anm_msgs/VehicleState','control_msgs/Report','float64','float64','float64','float64','float64']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       header,vehicle_state,ecu_report,speed_cmd,steer_cmd,lateral_error,heading_error,time_cost

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(observer, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.vehicle_state is None:
        self.vehicle_state = anm_msgs.msg.VehicleState()
      if self.ecu_report is None:
        self.ecu_report = control_msgs.msg.Report()
      if self.speed_cmd is None:
        self.speed_cmd = 0.
      if self.steer_cmd is None:
        self.steer_cmd = 0.
      if self.lateral_error is None:
        self.lateral_error = 0.
      if self.heading_error is None:
        self.heading_error = 0.
      if self.time_cost is None:
        self.time_cost = 0.
    else:
      self.header = std_msgs.msg.Header()
      self.vehicle_state = anm_msgs.msg.VehicleState()
      self.ecu_report = control_msgs.msg.Report()
      self.speed_cmd = 0.
      self.steer_cmd = 0.
      self.lateral_error = 0.
      self.heading_error = 0.
      self.time_cost = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs))
      _x = self.vehicle_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.vehicle_state.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_18d3I().pack(_x.vehicle_state.position.x, _x.vehicle_state.position.y, _x.vehicle_state.position.z, _x.vehicle_state.orientation.x, _x.vehicle_state.orientation.y, _x.vehicle_state.orientation.z, _x.vehicle_state.velocity.linear.x, _x.vehicle_state.velocity.linear.y, _x.vehicle_state.velocity.linear.z, _x.vehicle_state.velocity.angular.x, _x.vehicle_state.velocity.angular.y, _x.vehicle_state.velocity.angular.z, _x.vehicle_state.acceleration.linear.x, _x.vehicle_state.acceleration.linear.y, _x.vehicle_state.acceleration.linear.z, _x.vehicle_state.acceleration.angular.x, _x.vehicle_state.acceleration.angular.y, _x.vehicle_state.acceleration.angular.z, _x.ecu_report.header.seq, _x.ecu_report.header.stamp.secs, _x.ecu_report.header.stamp.nsecs))
      _x = self.ecu_report.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.ecu_report.control.Speed.header.seq, _x.ecu_report.control.Speed.header.stamp.secs, _x.ecu_report.control.Speed.header.stamp.nsecs))
      _x = self.ecu_report.control.Speed.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4d3I().pack(_x.ecu_report.control.Speed.priority, _x.ecu_report.control.Speed.gear, _x.ecu_report.control.Speed.speed, _x.ecu_report.control.Speed.acc, _x.ecu_report.control.Speed.torque, _x.ecu_report.control.Speed.brake, _x.ecu_report.control.Steer.header.seq, _x.ecu_report.control.Steer.header.stamp.secs, _x.ecu_report.control.Steer.header.stamp.nsecs))
      _x = self.ecu_report.control.Steer.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bd3I().pack(_x.ecu_report.control.Steer.priority, _x.ecu_report.control.Steer.steer, _x.ecu_report.control.ordermode.header.seq, _x.ecu_report.control.ordermode.header.stamp.secs, _x.ecu_report.control.ordermode.header.stamp.nsecs))
      _x = self.ecu_report.control.ordermode.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.ecu_report.control.ordermode.RainyLight, _x.ecu_report.vcu_torque_brake.Speed.header.seq, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.nsecs))
      _x = self.ecu_report.vcu_torque_brake.Speed.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4d3I().pack(_x.ecu_report.vcu_torque_brake.Speed.priority, _x.ecu_report.vcu_torque_brake.Speed.gear, _x.ecu_report.vcu_torque_brake.Speed.speed, _x.ecu_report.vcu_torque_brake.Speed.acc, _x.ecu_report.vcu_torque_brake.Speed.torque, _x.ecu_report.vcu_torque_brake.Speed.brake, _x.ecu_report.vcu_torque_brake.Steer.header.seq, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.nsecs))
      _x = self.ecu_report.vcu_torque_brake.Steer.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bd3I().pack(_x.ecu_report.vcu_torque_brake.Steer.priority, _x.ecu_report.vcu_torque_brake.Steer.steer, _x.ecu_report.vcu_torque_brake.ordermode.header.seq, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.secs, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.nsecs))
      _x = self.ecu_report.vcu_torque_brake.ordermode.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2BdB3d4B2d7f7B5d().pack(_x.ecu_report.vcu_torque_brake.ordermode.RainyLight, _x.ecu_report.motion.drive_mode, _x.ecu_report.motion.steer, _x.ecu_report.motion.gear, _x.ecu_report.motion.velocity, _x.ecu_report.brake.left_pressure_back, _x.ecu_report.brake.right_pressure_back, _x.ecu_report.brake.auto_park_state, _x.ecu_report.brake.auto_brake_enable, _x.ecu_report.brake.system_hot_warn, _x.ecu_report.brake.system_error_code, _x.ecu_report.brake.left_pressure_set, _x.ecu_report.brake.right_pressure_set, _x.ecu_report.brake.brake_pedal, _x.ecu_report.throttle.throttle_opening, _x.ecu_report.throttle.throttle_pedal, _x.ecu_report.wheel.front_left, _x.ecu_report.wheel.front_right, _x.ecu_report.wheel.rear_left, _x.ecu_report.wheel.rear_right, _x.ecu_report.wheel.statusfl, _x.ecu_report.wheel.statusfr, _x.ecu_report.wheel.statusrl, _x.ecu_report.wheel.statusrr, _x.ecu_report.manual.manual_estop, _x.ecu_report.manual.is_human_brake, _x.ecu_report.vehicle_work_mode.work_mode, _x.speed_cmd, _x.steer_cmd, _x.lateral_error, _x.heading_error, _x.time_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.vehicle_state is None:
        self.vehicle_state = anm_msgs.msg.VehicleState()
      if self.ecu_report is None:
        self.ecu_report = control_msgs.msg.Report()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.vehicle_state.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.vehicle_state.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.vehicle_state.position.x, _x.vehicle_state.position.y, _x.vehicle_state.position.z, _x.vehicle_state.orientation.x, _x.vehicle_state.orientation.y, _x.vehicle_state.orientation.z, _x.vehicle_state.velocity.linear.x, _x.vehicle_state.velocity.linear.y, _x.vehicle_state.velocity.linear.z, _x.vehicle_state.velocity.angular.x, _x.vehicle_state.velocity.angular.y, _x.vehicle_state.velocity.angular.z, _x.vehicle_state.acceleration.linear.x, _x.vehicle_state.acceleration.linear.y, _x.vehicle_state.acceleration.linear.z, _x.vehicle_state.acceleration.angular.x, _x.vehicle_state.acceleration.angular.y, _x.vehicle_state.acceleration.angular.z, _x.ecu_report.header.seq, _x.ecu_report.header.stamp.secs, _x.ecu_report.header.stamp.nsecs,) = _get_struct_18d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.ecu_report.control.Speed.header.seq, _x.ecu_report.control.Speed.header.stamp.secs, _x.ecu_report.control.Speed.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.control.Speed.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.control.Speed.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.ecu_report.control.Speed.priority, _x.ecu_report.control.Speed.gear, _x.ecu_report.control.Speed.speed, _x.ecu_report.control.Speed.acc, _x.ecu_report.control.Speed.torque, _x.ecu_report.control.Speed.brake, _x.ecu_report.control.Steer.header.seq, _x.ecu_report.control.Steer.header.stamp.secs, _x.ecu_report.control.Steer.header.stamp.nsecs,) = _get_struct_2B4d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.control.Steer.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.control.Steer.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 21
      (_x.ecu_report.control.Steer.priority, _x.ecu_report.control.Steer.steer, _x.ecu_report.control.ordermode.header.seq, _x.ecu_report.control.ordermode.header.stamp.secs, _x.ecu_report.control.ordermode.header.stamp.nsecs,) = _get_struct_Bd3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.control.ordermode.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.control.ordermode.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.ecu_report.control.ordermode.RainyLight, _x.ecu_report.vcu_torque_brake.Speed.header.seq, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.vcu_torque_brake.Speed.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.vcu_torque_brake.Speed.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.ecu_report.vcu_torque_brake.Speed.priority, _x.ecu_report.vcu_torque_brake.Speed.gear, _x.ecu_report.vcu_torque_brake.Speed.speed, _x.ecu_report.vcu_torque_brake.Speed.acc, _x.ecu_report.vcu_torque_brake.Speed.torque, _x.ecu_report.vcu_torque_brake.Speed.brake, _x.ecu_report.vcu_torque_brake.Steer.header.seq, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.nsecs,) = _get_struct_2B4d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.vcu_torque_brake.Steer.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.vcu_torque_brake.Steer.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 21
      (_x.ecu_report.vcu_torque_brake.Steer.priority, _x.ecu_report.vcu_torque_brake.Steer.steer, _x.ecu_report.vcu_torque_brake.ordermode.header.seq, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.secs, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.nsecs,) = _get_struct_Bd3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.vcu_torque_brake.ordermode.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.vcu_torque_brake.ordermode.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 130
      (_x.ecu_report.vcu_torque_brake.ordermode.RainyLight, _x.ecu_report.motion.drive_mode, _x.ecu_report.motion.steer, _x.ecu_report.motion.gear, _x.ecu_report.motion.velocity, _x.ecu_report.brake.left_pressure_back, _x.ecu_report.brake.right_pressure_back, _x.ecu_report.brake.auto_park_state, _x.ecu_report.brake.auto_brake_enable, _x.ecu_report.brake.system_hot_warn, _x.ecu_report.brake.system_error_code, _x.ecu_report.brake.left_pressure_set, _x.ecu_report.brake.right_pressure_set, _x.ecu_report.brake.brake_pedal, _x.ecu_report.throttle.throttle_opening, _x.ecu_report.throttle.throttle_pedal, _x.ecu_report.wheel.front_left, _x.ecu_report.wheel.front_right, _x.ecu_report.wheel.rear_left, _x.ecu_report.wheel.rear_right, _x.ecu_report.wheel.statusfl, _x.ecu_report.wheel.statusfr, _x.ecu_report.wheel.statusrl, _x.ecu_report.wheel.statusrr, _x.ecu_report.manual.manual_estop, _x.ecu_report.manual.is_human_brake, _x.ecu_report.vehicle_work_mode.work_mode, _x.speed_cmd, _x.steer_cmd, _x.lateral_error, _x.heading_error, _x.time_cost,) = _get_struct_2BdB3d4B2d7f7B5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_3I().pack(_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs))
      _x = self.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs))
      _x = self.vehicle_state.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self.vehicle_state.child_frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_18d3I().pack(_x.vehicle_state.position.x, _x.vehicle_state.position.y, _x.vehicle_state.position.z, _x.vehicle_state.orientation.x, _x.vehicle_state.orientation.y, _x.vehicle_state.orientation.z, _x.vehicle_state.velocity.linear.x, _x.vehicle_state.velocity.linear.y, _x.vehicle_state.velocity.linear.z, _x.vehicle_state.velocity.angular.x, _x.vehicle_state.velocity.angular.y, _x.vehicle_state.velocity.angular.z, _x.vehicle_state.acceleration.linear.x, _x.vehicle_state.acceleration.linear.y, _x.vehicle_state.acceleration.linear.z, _x.vehicle_state.acceleration.angular.x, _x.vehicle_state.acceleration.angular.y, _x.vehicle_state.acceleration.angular.z, _x.ecu_report.header.seq, _x.ecu_report.header.stamp.secs, _x.ecu_report.header.stamp.nsecs))
      _x = self.ecu_report.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_3I().pack(_x.ecu_report.control.Speed.header.seq, _x.ecu_report.control.Speed.header.stamp.secs, _x.ecu_report.control.Speed.header.stamp.nsecs))
      _x = self.ecu_report.control.Speed.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4d3I().pack(_x.ecu_report.control.Speed.priority, _x.ecu_report.control.Speed.gear, _x.ecu_report.control.Speed.speed, _x.ecu_report.control.Speed.acc, _x.ecu_report.control.Speed.torque, _x.ecu_report.control.Speed.brake, _x.ecu_report.control.Steer.header.seq, _x.ecu_report.control.Steer.header.stamp.secs, _x.ecu_report.control.Steer.header.stamp.nsecs))
      _x = self.ecu_report.control.Steer.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bd3I().pack(_x.ecu_report.control.Steer.priority, _x.ecu_report.control.Steer.steer, _x.ecu_report.control.ordermode.header.seq, _x.ecu_report.control.ordermode.header.stamp.secs, _x.ecu_report.control.ordermode.header.stamp.nsecs))
      _x = self.ecu_report.control.ordermode.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_B3I().pack(_x.ecu_report.control.ordermode.RainyLight, _x.ecu_report.vcu_torque_brake.Speed.header.seq, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.nsecs))
      _x = self.ecu_report.vcu_torque_brake.Speed.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2B4d3I().pack(_x.ecu_report.vcu_torque_brake.Speed.priority, _x.ecu_report.vcu_torque_brake.Speed.gear, _x.ecu_report.vcu_torque_brake.Speed.speed, _x.ecu_report.vcu_torque_brake.Speed.acc, _x.ecu_report.vcu_torque_brake.Speed.torque, _x.ecu_report.vcu_torque_brake.Speed.brake, _x.ecu_report.vcu_torque_brake.Steer.header.seq, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.nsecs))
      _x = self.ecu_report.vcu_torque_brake.Steer.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_Bd3I().pack(_x.ecu_report.vcu_torque_brake.Steer.priority, _x.ecu_report.vcu_torque_brake.Steer.steer, _x.ecu_report.vcu_torque_brake.ordermode.header.seq, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.secs, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.nsecs))
      _x = self.ecu_report.vcu_torque_brake.ordermode.header.frame_id
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_2BdB3d4B2d7f7B5d().pack(_x.ecu_report.vcu_torque_brake.ordermode.RainyLight, _x.ecu_report.motion.drive_mode, _x.ecu_report.motion.steer, _x.ecu_report.motion.gear, _x.ecu_report.motion.velocity, _x.ecu_report.brake.left_pressure_back, _x.ecu_report.brake.right_pressure_back, _x.ecu_report.brake.auto_park_state, _x.ecu_report.brake.auto_brake_enable, _x.ecu_report.brake.system_hot_warn, _x.ecu_report.brake.system_error_code, _x.ecu_report.brake.left_pressure_set, _x.ecu_report.brake.right_pressure_set, _x.ecu_report.brake.brake_pedal, _x.ecu_report.throttle.throttle_opening, _x.ecu_report.throttle.throttle_pedal, _x.ecu_report.wheel.front_left, _x.ecu_report.wheel.front_right, _x.ecu_report.wheel.rear_left, _x.ecu_report.wheel.rear_right, _x.ecu_report.wheel.statusfl, _x.ecu_report.wheel.statusfr, _x.ecu_report.wheel.statusrl, _x.ecu_report.wheel.statusrr, _x.ecu_report.manual.manual_estop, _x.ecu_report.manual.is_human_brake, _x.ecu_report.vehicle_work_mode.work_mode, _x.speed_cmd, _x.steer_cmd, _x.lateral_error, _x.heading_error, _x.time_cost))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.header is None:
        self.header = std_msgs.msg.Header()
      if self.vehicle_state is None:
        self.vehicle_state = anm_msgs.msg.VehicleState()
      if self.ecu_report is None:
        self.ecu_report = control_msgs.msg.Report()
      end = 0
      _x = self
      start = end
      end += 12
      (_x.header.seq, _x.header.stamp.secs, _x.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.vehicle_state.header.seq, _x.vehicle_state.header.stamp.secs, _x.vehicle_state.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.vehicle_state.header.frame_id = str[start:end]
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.vehicle_state.child_frame_id = str[start:end].decode('utf-8')
      else:
        self.vehicle_state.child_frame_id = str[start:end]
      _x = self
      start = end
      end += 156
      (_x.vehicle_state.position.x, _x.vehicle_state.position.y, _x.vehicle_state.position.z, _x.vehicle_state.orientation.x, _x.vehicle_state.orientation.y, _x.vehicle_state.orientation.z, _x.vehicle_state.velocity.linear.x, _x.vehicle_state.velocity.linear.y, _x.vehicle_state.velocity.linear.z, _x.vehicle_state.velocity.angular.x, _x.vehicle_state.velocity.angular.y, _x.vehicle_state.velocity.angular.z, _x.vehicle_state.acceleration.linear.x, _x.vehicle_state.acceleration.linear.y, _x.vehicle_state.acceleration.linear.z, _x.vehicle_state.acceleration.angular.x, _x.vehicle_state.acceleration.angular.y, _x.vehicle_state.acceleration.angular.z, _x.ecu_report.header.seq, _x.ecu_report.header.stamp.secs, _x.ecu_report.header.stamp.nsecs,) = _get_struct_18d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 12
      (_x.ecu_report.control.Speed.header.seq, _x.ecu_report.control.Speed.header.stamp.secs, _x.ecu_report.control.Speed.header.stamp.nsecs,) = _get_struct_3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.control.Speed.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.control.Speed.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.ecu_report.control.Speed.priority, _x.ecu_report.control.Speed.gear, _x.ecu_report.control.Speed.speed, _x.ecu_report.control.Speed.acc, _x.ecu_report.control.Speed.torque, _x.ecu_report.control.Speed.brake, _x.ecu_report.control.Steer.header.seq, _x.ecu_report.control.Steer.header.stamp.secs, _x.ecu_report.control.Steer.header.stamp.nsecs,) = _get_struct_2B4d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.control.Steer.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.control.Steer.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 21
      (_x.ecu_report.control.Steer.priority, _x.ecu_report.control.Steer.steer, _x.ecu_report.control.ordermode.header.seq, _x.ecu_report.control.ordermode.header.stamp.secs, _x.ecu_report.control.ordermode.header.stamp.nsecs,) = _get_struct_Bd3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.control.ordermode.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.control.ordermode.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 13
      (_x.ecu_report.control.ordermode.RainyLight, _x.ecu_report.vcu_torque_brake.Speed.header.seq, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Speed.header.stamp.nsecs,) = _get_struct_B3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.vcu_torque_brake.Speed.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.vcu_torque_brake.Speed.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 46
      (_x.ecu_report.vcu_torque_brake.Speed.priority, _x.ecu_report.vcu_torque_brake.Speed.gear, _x.ecu_report.vcu_torque_brake.Speed.speed, _x.ecu_report.vcu_torque_brake.Speed.acc, _x.ecu_report.vcu_torque_brake.Speed.torque, _x.ecu_report.vcu_torque_brake.Speed.brake, _x.ecu_report.vcu_torque_brake.Steer.header.seq, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.secs, _x.ecu_report.vcu_torque_brake.Steer.header.stamp.nsecs,) = _get_struct_2B4d3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.vcu_torque_brake.Steer.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.vcu_torque_brake.Steer.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 21
      (_x.ecu_report.vcu_torque_brake.Steer.priority, _x.ecu_report.vcu_torque_brake.Steer.steer, _x.ecu_report.vcu_torque_brake.ordermode.header.seq, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.secs, _x.ecu_report.vcu_torque_brake.ordermode.header.stamp.nsecs,) = _get_struct_Bd3I().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.ecu_report.vcu_torque_brake.ordermode.header.frame_id = str[start:end].decode('utf-8')
      else:
        self.ecu_report.vcu_torque_brake.ordermode.header.frame_id = str[start:end]
      _x = self
      start = end
      end += 130
      (_x.ecu_report.vcu_torque_brake.ordermode.RainyLight, _x.ecu_report.motion.drive_mode, _x.ecu_report.motion.steer, _x.ecu_report.motion.gear, _x.ecu_report.motion.velocity, _x.ecu_report.brake.left_pressure_back, _x.ecu_report.brake.right_pressure_back, _x.ecu_report.brake.auto_park_state, _x.ecu_report.brake.auto_brake_enable, _x.ecu_report.brake.system_hot_warn, _x.ecu_report.brake.system_error_code, _x.ecu_report.brake.left_pressure_set, _x.ecu_report.brake.right_pressure_set, _x.ecu_report.brake.brake_pedal, _x.ecu_report.throttle.throttle_opening, _x.ecu_report.throttle.throttle_pedal, _x.ecu_report.wheel.front_left, _x.ecu_report.wheel.front_right, _x.ecu_report.wheel.rear_left, _x.ecu_report.wheel.rear_right, _x.ecu_report.wheel.statusfl, _x.ecu_report.wheel.statusfr, _x.ecu_report.wheel.statusrl, _x.ecu_report.wheel.statusrr, _x.ecu_report.manual.manual_estop, _x.ecu_report.manual.is_human_brake, _x.ecu_report.vehicle_work_mode.work_mode, _x.speed_cmd, _x.steer_cmd, _x.lateral_error, _x.heading_error, _x.time_cost,) = _get_struct_2BdB3d4B2d7f7B5d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2BdB3d4B2d7f7B5d = None
def _get_struct_2BdB3d4B2d7f7B5d():
    global _struct_2BdB3d4B2d7f7B5d
    if _struct_2BdB3d4B2d7f7B5d is None:
        _struct_2BdB3d4B2d7f7B5d = struct.Struct("<2BdB3d4B2d7f7B5d")
    return _struct_2BdB3d4B2d7f7B5d
_struct_3I = None
def _get_struct_3I():
    global _struct_3I
    if _struct_3I is None:
        _struct_3I = struct.Struct("<3I")
    return _struct_3I
_struct_Bd3I = None
def _get_struct_Bd3I():
    global _struct_Bd3I
    if _struct_Bd3I is None:
        _struct_Bd3I = struct.Struct("<Bd3I")
    return _struct_Bd3I
_struct_B3I = None
def _get_struct_B3I():
    global _struct_B3I
    if _struct_B3I is None:
        _struct_B3I = struct.Struct("<B3I")
    return _struct_B3I
_struct_18d3I = None
def _get_struct_18d3I():
    global _struct_18d3I
    if _struct_18d3I is None:
        _struct_18d3I = struct.Struct("<18d3I")
    return _struct_18d3I
_struct_2B4d3I = None
def _get_struct_2B4d3I():
    global _struct_2B4d3I
    if _struct_2B4d3I is None:
        _struct_2B4d3I = struct.Struct("<2B4d3I")
    return _struct_2B4d3I
