# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_msgs/ReportWheel.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ReportWheel(genpy.Message):
  _md5sum = "c3a44de250eee4620714d052b512e107"
  _type = "control_msgs/ReportWheel"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float32 front_left
float32 front_right
float32 rear_left
float32 rear_right
uint8 statusfl
uint8 statusfr
uint8 statusrl
uint8 statusrr
"""
  __slots__ = ['front_left','front_right','rear_left','rear_right','statusfl','statusfr','statusrl','statusrr']
  _slot_types = ['float32','float32','float32','float32','uint8','uint8','uint8','uint8']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       front_left,front_right,rear_left,rear_right,statusfl,statusfr,statusrl,statusrr

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReportWheel, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.front_left is None:
        self.front_left = 0.
      if self.front_right is None:
        self.front_right = 0.
      if self.rear_left is None:
        self.rear_left = 0.
      if self.rear_right is None:
        self.rear_right = 0.
      if self.statusfl is None:
        self.statusfl = 0
      if self.statusfr is None:
        self.statusfr = 0
      if self.statusrl is None:
        self.statusrl = 0
      if self.statusrr is None:
        self.statusrr = 0
    else:
      self.front_left = 0.
      self.front_right = 0.
      self.rear_left = 0.
      self.rear_right = 0.
      self.statusfl = 0
      self.statusfr = 0
      self.statusrl = 0
      self.statusrr = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f4B().pack(_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.statusfl, _x.statusfr, _x.statusrl, _x.statusrr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.statusfl, _x.statusfr, _x.statusrl, _x.statusrr,) = _get_struct_4f4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f4B().pack(_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.statusfl, _x.statusfr, _x.statusrl, _x.statusrr))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 20
      (_x.front_left, _x.front_right, _x.rear_left, _x.rear_right, _x.statusfl, _x.statusfr, _x.statusrl, _x.statusrr,) = _get_struct_4f4B().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f4B = None
def _get_struct_4f4B():
    global _struct_4f4B
    if _struct_4f4B is None:
        _struct_4f4B = struct.Struct("<4f4B")
    return _struct_4f4B
