# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from control_msgs/ReportBrake.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class ReportBrake(genpy.Message):
  _md5sum = "c8b58fe12b43fe4b1c2d9a5950b7da37"
  _type = "control_msgs/ReportBrake"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """float64 left_pressure_back
float64 right_pressure_back
uint8 auto_park_state
uint8 auto_brake_enable
uint8 system_hot_warn
uint8 system_error_code
float64 left_pressure_set
float64 right_pressure_set
float32 brake_pedal
"""
  __slots__ = ['left_pressure_back','right_pressure_back','auto_park_state','auto_brake_enable','system_hot_warn','system_error_code','left_pressure_set','right_pressure_set','brake_pedal']
  _slot_types = ['float64','float64','uint8','uint8','uint8','uint8','float64','float64','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       left_pressure_back,right_pressure_back,auto_park_state,auto_brake_enable,system_hot_warn,system_error_code,left_pressure_set,right_pressure_set,brake_pedal

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(ReportBrake, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.left_pressure_back is None:
        self.left_pressure_back = 0.
      if self.right_pressure_back is None:
        self.right_pressure_back = 0.
      if self.auto_park_state is None:
        self.auto_park_state = 0
      if self.auto_brake_enable is None:
        self.auto_brake_enable = 0
      if self.system_hot_warn is None:
        self.system_hot_warn = 0
      if self.system_error_code is None:
        self.system_error_code = 0
      if self.left_pressure_set is None:
        self.left_pressure_set = 0.
      if self.right_pressure_set is None:
        self.right_pressure_set = 0.
      if self.brake_pedal is None:
        self.brake_pedal = 0.
    else:
      self.left_pressure_back = 0.
      self.right_pressure_back = 0.
      self.auto_park_state = 0
      self.auto_brake_enable = 0
      self.system_hot_warn = 0
      self.system_error_code = 0
      self.left_pressure_set = 0.
      self.right_pressure_set = 0.
      self.brake_pedal = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2d4B2df().pack(_x.left_pressure_back, _x.right_pressure_back, _x.auto_park_state, _x.auto_brake_enable, _x.system_hot_warn, _x.system_error_code, _x.left_pressure_set, _x.right_pressure_set, _x.brake_pedal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.left_pressure_back, _x.right_pressure_back, _x.auto_park_state, _x.auto_brake_enable, _x.system_hot_warn, _x.system_error_code, _x.left_pressure_set, _x.right_pressure_set, _x.brake_pedal,) = _get_struct_2d4B2df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2d4B2df().pack(_x.left_pressure_back, _x.right_pressure_back, _x.auto_park_state, _x.auto_brake_enable, _x.system_hot_warn, _x.system_error_code, _x.left_pressure_set, _x.right_pressure_set, _x.brake_pedal))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      _x = self
      start = end
      end += 40
      (_x.left_pressure_back, _x.right_pressure_back, _x.auto_park_state, _x.auto_brake_enable, _x.system_hot_warn, _x.system_error_code, _x.left_pressure_set, _x.right_pressure_set, _x.brake_pedal,) = _get_struct_2d4B2df().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2d4B2df = None
def _get_struct_2d4B2df():
    global _struct_2d4B2df
    if _struct_2d4B2df is None:
        _struct_2d4B2df = struct.Struct("<2d4B2df")
    return _struct_2d4B2df
