// Generated by gencpp from file control_msgs/ReportVehicleWorkMode.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_REPORTVEHICLEWORKMODE_H
#define CONTROL_MSGS_MESSAGE_REPORTVEHICLEWORKMODE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_msgs
{
template <class ContainerAllocator>
struct ReportVehicleWorkMode_
{
  typedef ReportVehicleWorkMode_<ContainerAllocator> Type;

  ReportVehicleWorkMode_()
    : work_mode(0)  {
    }
  ReportVehicleWorkMode_(const ContainerAllocator& _alloc)
    : work_mode(0)  {
  (void)_alloc;
    }



   typedef uint8_t _work_mode_type;
  _work_mode_type work_mode;





  typedef boost::shared_ptr< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> const> ConstPtr;

}; // struct ReportVehicleWorkMode_

typedef ::control_msgs::ReportVehicleWorkMode_<std::allocator<void> > ReportVehicleWorkMode;

typedef boost::shared_ptr< ::control_msgs::ReportVehicleWorkMode > ReportVehicleWorkModePtr;
typedef boost::shared_ptr< ::control_msgs::ReportVehicleWorkMode const> ReportVehicleWorkModeConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_driver_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/sensor_driver_msgs/msg'], 'control_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/control_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "fcfe851405844897c8730da81110283d";
  }

  static const char* value(const ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xfcfe851405844897ULL;
  static const uint64_t static_value2 = 0xc8730da81110283dULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_msgs/ReportVehicleWorkMode";
  }

  static const char* value(const ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 work_mode\n\
\n\
\n\
";
  }

  static const char* value(const ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.work_mode);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReportVehicleWorkMode_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_msgs::ReportVehicleWorkMode_<ContainerAllocator>& v)
  {
    s << indent << "work_mode: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.work_mode);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_REPORTVEHICLEWORKMODE_H
