// Generated by gencpp from file control_msgs/ReportHMI.msg
// DO NOT EDIT!


#ifndef CONTROL_MSGS_MESSAGE_REPORTHMI_H
#define CONTROL_MSGS_MESSAGE_REPORTHMI_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace control_msgs
{
template <class ContainerAllocator>
struct ReportHMI_
{
  typedef ReportHMI_<ContainerAllocator> Type;

  ReportHMI_()
    : manual_estop(0)
    , is_human_brake(0)  {
    }
  ReportHMI_(const ContainerAllocator& _alloc)
    : manual_estop(0)
    , is_human_brake(0)  {
  (void)_alloc;
    }



   typedef uint8_t _manual_estop_type;
  _manual_estop_type manual_estop;

   typedef uint8_t _is_human_brake_type;
  _is_human_brake_type is_human_brake;





  typedef boost::shared_ptr< ::control_msgs::ReportHMI_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::control_msgs::ReportHMI_<ContainerAllocator> const> ConstPtr;

}; // struct ReportHMI_

typedef ::control_msgs::ReportHMI_<std::allocator<void> > ReportHMI;

typedef boost::shared_ptr< ::control_msgs::ReportHMI > ReportHMIPtr;
typedef boost::shared_ptr< ::control_msgs::ReportHMI const> ReportHMIConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::control_msgs::ReportHMI_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::control_msgs::ReportHMI_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace control_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'nav_msgs': ['/opt/ros/kinetic/share/nav_msgs/cmake/../msg'], 'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'sensor_driver_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/sensor_driver_msgs/msg'], 'control_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/control_msgs/msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ReportHMI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::control_msgs::ReportHMI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ReportHMI_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::control_msgs::ReportHMI_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ReportHMI_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::control_msgs::ReportHMI_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::control_msgs::ReportHMI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f19a467eddf6f2a1b5c81ed415355fbf";
  }

  static const char* value(const ::control_msgs::ReportHMI_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf19a467eddf6f2a1ULL;
  static const uint64_t static_value2 = 0xb5c81ed415355fbfULL;
};

template<class ContainerAllocator>
struct DataType< ::control_msgs::ReportHMI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "control_msgs/ReportHMI";
  }

  static const char* value(const ::control_msgs::ReportHMI_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::control_msgs::ReportHMI_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 manual_estop\n\
uint8 is_human_brake \n\
";
  }

  static const char* value(const ::control_msgs::ReportHMI_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::control_msgs::ReportHMI_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.manual_estop);
      stream.next(m.is_human_brake);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReportHMI_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::control_msgs::ReportHMI_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::control_msgs::ReportHMI_<ContainerAllocator>& v)
  {
    s << indent << "manual_estop: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.manual_estop);
    s << indent << "is_human_brake: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.is_human_brake);
  }
};

} // namespace message_operations
} // namespace ros

#endif // CONTROL_MSGS_MESSAGE_REPORTHMI_H
