(cl:in-package control_msgs-msg)
(cl:export '(LEFT_PRESSURE_BACK-VAL
          LEFT_PRESSURE_BACK
          RIGHT_PRESSURE_BACK-VAL
          RIGHT_PRESSURE_BACK
          AUTO_PARK_STATE-VAL
          AUTO_PARK_STATE
          AUTO_BRAKE_ENABLE-VAL
          AUTO_BRAKE_ENABLE
          SYSTEM_HOT_WARN-VAL
          SYSTEM_HOT_WARN
          SYSTEM_ERROR_CODE-VAL
          SYSTEM_ERROR_CODE
          LEFT_PRESSURE_SET-VAL
          LEFT_PRESSURE_SET
          RIGHT_PRESSURE_SET-VAL
          RIGHT_PRESSURE_SET
          BRAKE_PEDAL-VAL
          BRAKE_PEDAL
))