// Generated by gencpp from file three_one_msgs/ControlSteer.msg
// DO NOT EDIT!


#ifndef THREE_ONE_MSGS_MESSAGE_CONTROLSTEER_H
#define THREE_ONE_MSGS_MESSAGE_CONTROLSTEER_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace three_one_msgs
{
template <class ContainerAllocator>
struct ControlSteer_
{
  typedef ControlSteer_<ContainerAllocator> Type;

  ControlSteer_()
    : priority(0)
    , curvature(0.0)  {
    }
  ControlSteer_(const ContainerAllocator& _alloc)
    : priority(0)
    , curvature(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _priority_type;
  _priority_type priority;

   typedef double _curvature_type;
  _curvature_type curvature;





  typedef boost::shared_ptr< ::three_one_msgs::ControlSteer_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::three_one_msgs::ControlSteer_<ContainerAllocator> const> ConstPtr;

}; // struct ControlSteer_

typedef ::three_one_msgs::ControlSteer_<std::allocator<void> > ControlSteer;

typedef boost::shared_ptr< ::three_one_msgs::ControlSteer > ControlSteerPtr;
typedef boost::shared_ptr< ::three_one_msgs::ControlSteer const> ControlSteerConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::three_one_msgs::ControlSteer_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::three_one_msgs::ControlSteer_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace three_one_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'three_one_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/three_one_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ControlSteer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ControlSteer_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ControlSteer_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "dfb9884ac74fdee49105f987268ecda4";
  }

  static const char* value(const ::three_one_msgs::ControlSteer_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xdfb9884ac74fdee4ULL;
  static const uint64_t static_value2 = 0x9105f987268ecda4ULL;
};

template<class ContainerAllocator>
struct DataType< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "three_one_msgs/ControlSteer";
  }

  static const char* value(const ::three_one_msgs::ControlSteer_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 priority\n\
float64 curvature\n\
";
  }

  static const char* value(const ::three_one_msgs::ControlSteer_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.priority);
      stream.next(m.curvature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ControlSteer_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::three_one_msgs::ControlSteer_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::three_one_msgs::ControlSteer_<ContainerAllocator>& v)
  {
    s << indent << "priority: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.priority);
    s << indent << "curvature: ";
    Printer<double>::stream(s, indent + "  ", v.curvature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THREE_ONE_MSGS_MESSAGE_CONTROLSTEER_H
