// Generated by gencpp from file three_one_msgs/RawdataSend.msg
// DO NOT EDIT!


#ifndef THREE_ONE_MSGS_MESSAGE_RAWDATASEND_H
#define THREE_ONE_MSGS_MESSAGE_RAWDATASEND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace three_one_msgs
{
template <class ContainerAllocator>
struct RawdataSend_
{
  typedef RawdataSend_<ContainerAllocator> Type;

  RawdataSend_()
    : ros_time(0.0)
    , data()  {
    }
  RawdataSend_(const ContainerAllocator& _alloc)
    : ros_time(0.0)
    , data(_alloc)  {
  (void)_alloc;
    }



   typedef double _ros_time_type;
  _ros_time_type ros_time;

   typedef std::vector<uint8_t, typename ContainerAllocator::template rebind<uint8_t>::other >  _data_type;
  _data_type data;





  typedef boost::shared_ptr< ::three_one_msgs::RawdataSend_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::three_one_msgs::RawdataSend_<ContainerAllocator> const> ConstPtr;

}; // struct RawdataSend_

typedef ::three_one_msgs::RawdataSend_<std::allocator<void> > RawdataSend;

typedef boost::shared_ptr< ::three_one_msgs::RawdataSend > RawdataSendPtr;
typedef boost::shared_ptr< ::three_one_msgs::RawdataSend const> RawdataSendConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::three_one_msgs::RawdataSend_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::three_one_msgs::RawdataSend_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace three_one_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'three_one_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/three_one_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::RawdataSend_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::RawdataSend_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::RawdataSend_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a34d701bf319ec12f678fa7cb20e57e3";
  }

  static const char* value(const ::three_one_msgs::RawdataSend_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa34d701bf319ec12ULL;
  static const uint64_t static_value2 = 0xf678fa7cb20e57e3ULL;
};

template<class ContainerAllocator>
struct DataType< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
{
  static const char* value()
  {
    return "three_one_msgs/RawdataSend";
  }

  static const char* value(const ::three_one_msgs::RawdataSend_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 ros_time\n\
uint8[] data\n\
";
  }

  static const char* value(const ::three_one_msgs::RawdataSend_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ros_time);
      stream.next(m.data);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RawdataSend_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::three_one_msgs::RawdataSend_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::three_one_msgs::RawdataSend_<ContainerAllocator>& v)
  {
    s << indent << "ros_time: ";
    Printer<double>::stream(s, indent + "  ", v.ros_time);
    s << indent << "data[]" << std::endl;
    for (size_t i = 0; i < v.data.size(); ++i)
    {
      s << indent << "  data[" << i << "]: ";
      Printer<uint8_t>::stream(s, indent + "  ", v.data[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // THREE_ONE_MSGS_MESSAGE_RAWDATASEND_H
