// Generated by gencpp from file three_one_msgs/ReportGiveBack.msg
// DO NOT EDIT!


#ifndef THREE_ONE_MSGS_MESSAGE_REPORTGIVEBACK_H
#define THREE_ONE_MSGS_MESSAGE_REPORTGIVEBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace three_one_msgs
{
template <class ContainerAllocator>
struct ReportGiveBack_
{
  typedef ReportGiveBack_<ContainerAllocator> Type;

  ReportGiveBack_()
    : left_wheel_expect_speed(0.0)
    , right_wheel_expect_speed(0.0)  {
    }
  ReportGiveBack_(const ContainerAllocator& _alloc)
    : left_wheel_expect_speed(0.0)
    , right_wheel_expect_speed(0.0)  {
  (void)_alloc;
    }



   typedef float _left_wheel_expect_speed_type;
  _left_wheel_expect_speed_type left_wheel_expect_speed;

   typedef float _right_wheel_expect_speed_type;
  _right_wheel_expect_speed_type right_wheel_expect_speed;





  typedef boost::shared_ptr< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> const> ConstPtr;

}; // struct ReportGiveBack_

typedef ::three_one_msgs::ReportGiveBack_<std::allocator<void> > ReportGiveBack;

typedef boost::shared_ptr< ::three_one_msgs::ReportGiveBack > ReportGiveBackPtr;
typedef boost::shared_ptr< ::three_one_msgs::ReportGiveBack const> ReportGiveBackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::three_one_msgs::ReportGiveBack_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace three_one_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'three_one_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/three_one_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a412fdf7ba4df281362ad0892df1c4a0";
  }

  static const char* value(const ::three_one_msgs::ReportGiveBack_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa412fdf7ba4df281ULL;
  static const uint64_t static_value2 = 0x362ad0892df1c4a0ULL;
};

template<class ContainerAllocator>
struct DataType< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "three_one_msgs/ReportGiveBack";
  }

  static const char* value(const ::three_one_msgs::ReportGiveBack_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 left_wheel_expect_speed\n\
float32 right_wheel_expect_speed\n\
";
  }

  static const char* value(const ::three_one_msgs::ReportGiveBack_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.left_wheel_expect_speed);
      stream.next(m.right_wheel_expect_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReportGiveBack_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::three_one_msgs::ReportGiveBack_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::three_one_msgs::ReportGiveBack_<ContainerAllocator>& v)
  {
    s << indent << "left_wheel_expect_speed: ";
    Printer<float>::stream(s, indent + "  ", v.left_wheel_expect_speed);
    s << indent << "right_wheel_expect_speed: ";
    Printer<float>::stream(s, indent + "  ", v.right_wheel_expect_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THREE_ONE_MSGS_MESSAGE_REPORTGIVEBACK_H
