// Generated by gencpp from file three_one_msgs/ReportMotion.msg
// DO NOT EDIT!


#ifndef THREE_ONE_MSGS_MESSAGE_REPORTMOTION_H
#define THREE_ONE_MSGS_MESSAGE_REPORTMOTION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace three_one_msgs
{
template <class ContainerAllocator>
struct ReportMotion_
{
  typedef ReportMotion_<ContainerAllocator> Type;

  ReportMotion_()
    : spin(0)
    , park(0)
    , current_gear(0)
    , left_wheel_rotate(0)
    , right_wheel_rotate(0)
    , left_motor_rpm(0)
    , right_motor_rpm(0)
    , mechanical_brake(0.0)
    , vehicle_speed(0.0)
    , left_wheel_speed(0.0)
    , right_wheel_speed(0.0)
    , curvature(0.0)  {
    }
  ReportMotion_(const ContainerAllocator& _alloc)
    : spin(0)
    , park(0)
    , current_gear(0)
    , left_wheel_rotate(0)
    , right_wheel_rotate(0)
    , left_motor_rpm(0)
    , right_motor_rpm(0)
    , mechanical_brake(0.0)
    , vehicle_speed(0.0)
    , left_wheel_speed(0.0)
    , right_wheel_speed(0.0)
    , curvature(0.0)  {
  (void)_alloc;
    }



   typedef uint8_t _spin_type;
  _spin_type spin;

   typedef uint8_t _park_type;
  _park_type park;

   typedef uint8_t _current_gear_type;
  _current_gear_type current_gear;

   typedef uint8_t _left_wheel_rotate_type;
  _left_wheel_rotate_type left_wheel_rotate;

   typedef uint8_t _right_wheel_rotate_type;
  _right_wheel_rotate_type right_wheel_rotate;

   typedef uint16_t _left_motor_rpm_type;
  _left_motor_rpm_type left_motor_rpm;

   typedef uint16_t _right_motor_rpm_type;
  _right_motor_rpm_type right_motor_rpm;

   typedef float _mechanical_brake_type;
  _mechanical_brake_type mechanical_brake;

   typedef double _vehicle_speed_type;
  _vehicle_speed_type vehicle_speed;

   typedef double _left_wheel_speed_type;
  _left_wheel_speed_type left_wheel_speed;

   typedef double _right_wheel_speed_type;
  _right_wheel_speed_type right_wheel_speed;

   typedef float _curvature_type;
  _curvature_type curvature;





  typedef boost::shared_ptr< ::three_one_msgs::ReportMotion_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::three_one_msgs::ReportMotion_<ContainerAllocator> const> ConstPtr;

}; // struct ReportMotion_

typedef ::three_one_msgs::ReportMotion_<std::allocator<void> > ReportMotion;

typedef boost::shared_ptr< ::three_one_msgs::ReportMotion > ReportMotionPtr;
typedef boost::shared_ptr< ::three_one_msgs::ReportMotion const> ReportMotionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::three_one_msgs::ReportMotion_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::three_one_msgs::ReportMotion_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace three_one_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'three_one_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/three_one_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ReportMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ReportMotion_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ReportMotion_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "60fe6a6e7ba2e99db01da0cfbfd1bb49";
  }

  static const char* value(const ::three_one_msgs::ReportMotion_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x60fe6a6e7ba2e99dULL;
  static const uint64_t static_value2 = 0xb01da0cfbfd1bb49ULL;
};

template<class ContainerAllocator>
struct DataType< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "three_one_msgs/ReportMotion";
  }

  static const char* value(const ::three_one_msgs::ReportMotion_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint8 spin\n\
uint8 park\n\
uint8 current_gear\n\
uint8 left_wheel_rotate\n\
uint8 right_wheel_rotate\n\
uint16 left_motor_rpm\n\
uint16 right_motor_rpm\n\
float32 mechanical_brake\n\
float64 vehicle_speed\n\
float64 left_wheel_speed  # signed\n\
float64 right_wheel_speed  # signed\n\
float32 curvature\n\
";
  }

  static const char* value(const ::three_one_msgs::ReportMotion_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.spin);
      stream.next(m.park);
      stream.next(m.current_gear);
      stream.next(m.left_wheel_rotate);
      stream.next(m.right_wheel_rotate);
      stream.next(m.left_motor_rpm);
      stream.next(m.right_motor_rpm);
      stream.next(m.mechanical_brake);
      stream.next(m.vehicle_speed);
      stream.next(m.left_wheel_speed);
      stream.next(m.right_wheel_speed);
      stream.next(m.curvature);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReportMotion_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::three_one_msgs::ReportMotion_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::three_one_msgs::ReportMotion_<ContainerAllocator>& v)
  {
    s << indent << "spin: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.spin);
    s << indent << "park: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.park);
    s << indent << "current_gear: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.current_gear);
    s << indent << "left_wheel_rotate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.left_wheel_rotate);
    s << indent << "right_wheel_rotate: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.right_wheel_rotate);
    s << indent << "left_motor_rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.left_motor_rpm);
    s << indent << "right_motor_rpm: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.right_motor_rpm);
    s << indent << "mechanical_brake: ";
    Printer<float>::stream(s, indent + "  ", v.mechanical_brake);
    s << indent << "vehicle_speed: ";
    Printer<double>::stream(s, indent + "  ", v.vehicle_speed);
    s << indent << "left_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.left_wheel_speed);
    s << indent << "right_wheel_speed: ";
    Printer<double>::stream(s, indent + "  ", v.right_wheel_speed);
    s << indent << "curvature: ";
    Printer<float>::stream(s, indent + "  ", v.curvature);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THREE_ONE_MSGS_MESSAGE_REPORTMOTION_H
