// Generated by gencpp from file three_one_msgs/ReportDistance.msg
// DO NOT EDIT!


#ifndef THREE_ONE_MSGS_MESSAGE_REPORTDISTANCE_H
#define THREE_ONE_MSGS_MESSAGE_REPORTDISTANCE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace three_one_msgs
{
template <class ContainerAllocator>
struct ReportDistance_
{
  typedef ReportDistance_<ContainerAllocator> Type;

  ReportDistance_()
    : mileage(0)
    , left_pulse(0)
    , right_pulse(0)
    , left_distance(0.0)
    , right_distance(0.0)  {
    }
  ReportDistance_(const ContainerAllocator& _alloc)
    : mileage(0)
    , left_pulse(0)
    , right_pulse(0)
    , left_distance(0.0)
    , right_distance(0.0)  {
  (void)_alloc;
    }



   typedef uint32_t _mileage_type;
  _mileage_type mileage;

   typedef uint32_t _left_pulse_type;
  _left_pulse_type left_pulse;

   typedef uint32_t _right_pulse_type;
  _right_pulse_type right_pulse;

   typedef double _left_distance_type;
  _left_distance_type left_distance;

   typedef double _right_distance_type;
  _right_distance_type right_distance;





  typedef boost::shared_ptr< ::three_one_msgs::ReportDistance_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::three_one_msgs::ReportDistance_<ContainerAllocator> const> ConstPtr;

}; // struct ReportDistance_

typedef ::three_one_msgs::ReportDistance_<std::allocator<void> > ReportDistance;

typedef boost::shared_ptr< ::three_one_msgs::ReportDistance > ReportDistancePtr;
typedef boost::shared_ptr< ::three_one_msgs::ReportDistance const> ReportDistanceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::three_one_msgs::ReportDistance_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::three_one_msgs::ReportDistance_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace three_one_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'three_one_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/three_one_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::three_one_msgs::ReportDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::three_one_msgs::ReportDistance_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::three_one_msgs::ReportDistance_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "11d828c6b9eb85d8fbb317377ee4beba";
  }

  static const char* value(const ::three_one_msgs::ReportDistance_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x11d828c6b9eb85d8ULL;
  static const uint64_t static_value2 = 0xfbb317377ee4bebaULL;
};

template<class ContainerAllocator>
struct DataType< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "three_one_msgs/ReportDistance";
  }

  static const char* value(const ::three_one_msgs::ReportDistance_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 mileage\n\
uint32 left_pulse\n\
uint32 right_pulse\n\
float64 left_distance\n\
float64 right_distance\n\
";
  }

  static const char* value(const ::three_one_msgs::ReportDistance_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.mileage);
      stream.next(m.left_pulse);
      stream.next(m.right_pulse);
      stream.next(m.left_distance);
      stream.next(m.right_distance);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ReportDistance_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::three_one_msgs::ReportDistance_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::three_one_msgs::ReportDistance_<ContainerAllocator>& v)
  {
    s << indent << "mileage: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.mileage);
    s << indent << "left_pulse: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.left_pulse);
    s << indent << "right_pulse: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.right_pulse);
    s << indent << "left_distance: ";
    Printer<double>::stream(s, indent + "  ", v.left_distance);
    s << indent << "right_distance: ";
    Printer<double>::stream(s, indent + "  ", v.right_distance);
  }
};

} // namespace message_operations
} // namespace ros

#endif // THREE_ONE_MSGS_MESSAGE_REPORTDISTANCE_H
