// Generated by gencpp from file movobsplan_msgs/Movobspoints.msg
// DO NOT EDIT!


#ifndef MOVOBSPLAN_MSGS_MESSAGE_MOVOBSPOINTS_H
#define MOVOBSPLAN_MSGS_MESSAGE_MOVOBSPOINTS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <movobsplan_msgs/Movobspoint.h>

namespace movobsplan_msgs
{
template <class ContainerAllocator>
struct Movobspoints_
{
  typedef Movobspoints_<ContainerAllocator> Type;

  Movobspoints_()
    : header()
    , dymipoints()  {
    }
  Movobspoints_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , dymipoints(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef std::vector< ::movobsplan_msgs::Movobspoint_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::movobsplan_msgs::Movobspoint_<ContainerAllocator> >::other >  _dymipoints_type;
  _dymipoints_type dymipoints;





  typedef boost::shared_ptr< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> const> ConstPtr;

}; // struct Movobspoints_

typedef ::movobsplan_msgs::Movobspoints_<std::allocator<void> > Movobspoints;

typedef boost::shared_ptr< ::movobsplan_msgs::Movobspoints > MovobspointsPtr;
typedef boost::shared_ptr< ::movobsplan_msgs::Movobspoints const> MovobspointsConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::movobsplan_msgs::Movobspoints_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace movobsplan_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'movobsplan_msgs': ['/home/bit2/0603_project/tang_ws/src/msgs/movobsplan_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f332c1b2f057ff022a7fac3fdfcee363";
  }

  static const char* value(const ::movobsplan_msgs::Movobspoints_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf332c1b2f057ff02ULL;
  static const uint64_t static_value2 = 0x2a7fac3fdfcee363ULL;
};

template<class ContainerAllocator>
struct DataType< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "movobsplan_msgs/Movobspoints";
  }

  static const char* value(const ::movobsplan_msgs::Movobspoints_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
{
  static const char* value()
  {
    return "std_msgs/Header header\n\
Movobspoint[] dymipoints\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: movobsplan_msgs/Movobspoint\n\
geometry_msgs/Point position\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::movobsplan_msgs::Movobspoints_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.dymipoints);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Movobspoints_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::movobsplan_msgs::Movobspoints_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::movobsplan_msgs::Movobspoints_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "dymipoints[]" << std::endl;
    for (size_t i = 0; i < v.dymipoints.size(); ++i)
    {
      s << indent << "  dymipoints[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::movobsplan_msgs::Movobspoint_<ContainerAllocator> >::stream(s, indent + "    ", v.dymipoints[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVOBSPLAN_MSGS_MESSAGE_MOVOBSPOINTS_H
